name: CI and Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
    paths:
      - 'src/**'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml@main

  publish:
    name: Publish Python distribution to PyPI and TestPyPI
    needs: ci
    uses: ./.github/workflows/publish.yml@main
