name: CI and Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
    paths:
      - 'src/**'

jobs:
  # Call CI
  ci:
    uses: .github/workflows/ci.yml@main
  # Call Publish Python distribution to PyPI and TestPyPI
  publish:
    needs: ci
    uses: .github/workflows/publish.yml@main
