name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'requirements_pytest.txt'

jobs:
  ci-linux:
    name: CI for Linux
    uses: ./.github/workflows/ci-linux.yml

  ci-macos:
    name: CI for macOS
    uses: ./.github/workflows/ci-macos.yml

  ci-windows:
    name: CI for Windows
    uses: ./.github/workflows/ci-windows.yml
