name: CI

on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
      ref:
        required: false
        type: string

jobs:
  ci-linux:
    name: CI for Linux
    uses: ./.github/workflows/ci-linux.yml
    with:
      ref: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}

  ci-macos:
    name: CI for macOS
    uses: ./.github/workflows/ci-macos.yml
    with:
      ref: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}

  ci-windows:
    name: CI for Windows
    uses: ./.github/workflows/ci-windows.yml
    with:
      ref: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
