# CI test suite. Simultaneously runs test cases for the supported platforms.
#
# Runs on any pull request to the main branch. This workflow can also be called
# manually or through another workflow.
#
# CI → CI for Linux
#    ↳ CI for macOS
#    ↳ CI for Windows
#
name: CI

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'requirements_pytest.txt'

jobs:
  ci-linux:
    name: CI for Linux
    uses: ./.github/workflows/ci-linux.yml

  ci-macos:
    name: CI for macOS
    uses: ./.github/workflows/ci-macos.yml
    secrets: inherit

  ci-windows:
    name: CI for Windows
    uses: ./.github/workflows/ci-windows.yml
