# Main workflow.
#
# Upon a push to the main branch, runs the CI test suite then the publishing
# workflow. Skips the CI test suite if publishing to PyPI.
#
# Run CI test suite → Build then Publish Python distribution
#
name: Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
    paths:
      - 'src/**'

jobs:
  ci:
    name: Run CI test suite
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  publish:
    name: Build then Publish Python distribution
    needs: ci
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/publish.yml
